name: Publish Docker image
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

env:
  IMAGE_REPOSITORY: angribot/snell

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Set build date
        run: |
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
          push: true
          tags: |
            ${{ env.IMAGE_REPOSITORY }}
          platforms: |
            linux/amd64
